name: Feature Branch CI

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/**'
      - 'README.md'
    branches-ignore:
      - 'master'
      - 'develop'
      - 'release*'

jobs:
  build:
    name: Feature Branch CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set up Maven
        run: cp build.settings.xml ~/.m2/settings.xml
      - name: Maven Build
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Ddockerfile.skip=true -B -V
        env:
          GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
      - name: Maven Verify
        run: mvn verify -B
